#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Mar 20 10:33:51 CET 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_receiver_behav -key {Behavioral:sim_1:Functional:test_receiver} -tclbatch test_receiver.tcl -view /home/elkhatir/Bureau/be_mac/BE_MAC/test_receiver_behav.wcfg -log simulate.log"
xsim test_receiver_behav -key {Behavioral:sim_1:Functional:test_receiver} -tclbatch test_receiver.tcl -view /home/elkhatir/Bureau/be_mac/BE_MAC/test_receiver_behav.wcfg -log simulate.log

